### ISSUE TITLE
A bug about training a model for online mapping

### ISSUE THREAD

**Issue by 1Hun0ter1** [yuantianyuan01/PreSight#2]
For Online Mapping：

# model with priors
bash tools/dist_train.sh ./configs/smn_wcamprior_480_100x50_24e_randomdrop.py 8 # 8-GPU training
should be ->
bash tools/dist_train.sh ./plugin/configs/smn_wcamprior_480_100x50_24e_randomdrop.py 8 # 8-GPU training?

**Comment by yuantianyuan01** [comment]
Sorry, it is a typo and it should be `./plugin/configs/smn_wcamprior_480_100x50_24e_randomdrop.py`. Thank you for pointing it out!
