### ISSUE TITLE
About a typo 

### ISSUE THREAD

**Issue by 1Hun0ter1** [yuantianyuan01/PreSight#5]
**For Occupancy**

b. Create annotations for our proposed new data split:
`python tools/create_data_bevdet.py --data-root ./data/nuscenes --extra_tag priorsplit`
->
`python tools/create_data_bevdet.py --data-root ./data/nuscenes --extra-tag priorsplit`

**Comment by yuantianyuan01** [comment]
Thanks for pointing it out. I am getting it fixed. If you find any errors else, feel free to let me know. Appreciate the help!
